# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01e99f8830660e14405203e94b2e44b45977fc5d91fbebd3c29eb8cd2ffa7d52904aec2a92e2fd05b25b8dc5be24251ff654f77fed58a6a9282530fbd8491b20

test:
  secret_key_base: 05cce0023b95313b2549611d237acba980ac3eca9e03415a1f864e01969b33e469cad940ae6138cc13e6d652947310f8784d5f8171f63efdbf0ba1ce116281f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
